# Лабораторна робота "Операції над масивами NumPy"

__Метою__ лабораторної роботи є набуття практичних навичок та закріплення теоретичних знань по обробці великих однорідних наборів даних які розташовані у вигляді масивів бібліотеки __NumPy__.

Виконати послідовно завдання в секціях, попередню засвоївши наведені приклади
В завданнях продовжити написання коду замість `...`. 

__Імена змінних в завданнях змінювати не можна!__

### Предвстановлення

In [2]:
# Імпортувати бібліотеку numpy з аліасом np
import numpy as np

In [2]:
# Вивід таблиці відповідності кодів типів даних в NumPy
import pandas as pd
dtypes = pd.DataFrame(
    {
        'Type': ['int8', 'uint8', 'int16', 'uint16', 'int32', 'uint32', 'int64', 'uint64', 'float16', 'float32', 'float64', 'float128', 'complex64', 'complex128', 'bool', 'object', 'string_', 'unicode_'],
        'Type Code': ['i1', 'u1', 'i2', 'u2', 'i4', 'u4', 'i8', 'u8', 'f2', 'f4 or f', 'f8 or d', 'f16 or g', 'c8', 'c16', '', 'O', 'S', 'U']
    }
)

dtypes

Type Type Code
0         int8        i1
1        uint8        u1
2        int16        i2
3       uint16        u2
4        int32        i4
5       uint32        u4
6        int64        i8
7       uint64        u8
8      float16        f2
9      float32   f4 or f
10     float64   f8 or d
11    float128  f16 or g
12   complex64        c8
13  complex128       c16
14        bool          
15      object         O
16     string_         S
17    unicode_         U

## 1. Створення та інспектування _np-массивів_

### ПРИКЛАДИ

In [5]:
# Створити 1-вимірний масив з 5 цілочисельних елементів 

arr = np.array([23, 42, 13, 7, 0])
print(arr)

Object `array` not found.
[23 42 13  7  0]


In [6]:
# Інспектування массива
np.info(arr)

class:  ndarray
shape:  (5,)
strides:  (4,)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x283b4c5f7c0
byteorder:  little
byteswap:  False
type: int32


In [69]:
# створити 2-мірний масив з цілим типом даних у 2-х байтовому форматі
arr = np.array([[1,2,3], [4,5,6]], dtype='i2')
print(arr)

[[1 2 3]
 [4 5 6]]


In [8]:
# створити масив із  значень в інтервалі 0 - 20 з кроком 2
# np.arange(start, stop, step)
arr = np.arange(0, 20, 2)  
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [121]:
# створити масив із 20 рівномірно розміщених значень в інтервалі 0 - 10 
# np.linspace(start, stop, num_of_elements) 
arr = np.linspace(0, 10, 20)
print(arr)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [9]:
# створити масив 3х3 випадкових значень 
arr = np.random.rand(3, 3)
print(arr)

[[0.64305116 0.12806391 0.92567906]
 [0.51912687 0.01250736 0.3243641 ]
 [0.05720272 0.56331912 0.16539876]]


In [10]:
# створення нульвих, одиничних та заповнених масивів
zeros = np.zeros((2,3), dtype='i4')
print(zeros)
ones = np.ones((2,3))
print(ones)
filled = np.full((2,3), 123)
print(filled)

[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[123 123 123]
 [123 123 123]]


In [11]:
print(arr, end="\n...\n")
# інспектування типу массиву `dtype`
print(arr.dtype)
# інспектування розмірності массиву `shape`
print(arr.shape)
# інспектування довжини масиву `len`
print(len(arr))
# інспектування кількості вимірів масиву `ndim`
print(arr.ndim)
# інспектування кількості елементів в масиві `size`
print(arr.size)
# інспектування коількості байтів на елемент `itemsize`
print(arr.itemsize)
# інспектування кількості пам'яти під масив `nbytes`
print(arr.nbytes)

[[0.64305116 0.12806391 0.92567906]
 [0.51912687 0.01250736 0.3243641 ]
 [0.05720272 0.56331912 0.16539876]]
...
float64
(3, 3)
3
2
9
8
72


In [12]:
arr.__sizeof__()

192

### ЗАВДАННЯ 1

In [15]:
### ЗАВДАННЯ 1.1: створити та проінспектувати масив 3х4 з ім'ям arr1_1, який містить числа з плавоючою точкою 
arr1_1 = np.full((3,4), 1.23)
print(arr1_1)

[[1.23 1.23 1.23 1.23]
 [1.23 1.23 1.23 1.23]
 [1.23 1.23 1.23 1.23]]


In [14]:
### ЗАВДАННЯ 1.2: створити одномірний масив з 5 строкових елементів
arr1_2 = np.array([23, 42, 13, 7, 0])
print(arr1_2)

[23 42 13  7  0]


In [92]:
### ЗАВДАННЯ 1.3: створити одиничний масив 3х4 чисел з плаваючою точкою
arr1_3 = np.ones((3,4))
print(arr1_3)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## 2. Перетворення форми та типу массивів

### ПРИКЛАДИ

In [22]:
# створити 2-мірний float-масив (2х5) з лінійного int-списка 
spisok = list(range(0,10))
arr = np.array(spisok)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [18]:
#преретворити форму масива `reshape` 
arr = arr.reshape((2,5))
print(arr)
print(arr.dtype)

[[0 1 2 3 4]
 [5 6 7 8 9]]
int32


In [23]:
# -- 3 перетворити тип масива `astype`
arr = arr.astype('float64')
print(arr)
print(arr.dtype)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
float64


In [24]:
# 'вирівняти' 2-мірний масив
arr = arr.flatten()
print(arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### ЗАВДАННЯ 2

In [40]:
### ЗАВДАННЯ 2.1: створити 3-мірний масив (3х1х3) логічного 'False'
arr2_1 =np.array([False]*9).reshape(3,1,3)
...
print(arr2_1)
print(arr2_1.dtype)

[[[False False False]]

 [[False False False]]

 [[False False False]]]
bool


In [47]:
### ЗАВДАННЯ 2.2: перетворити масив arr2_1 в 2-мірний масив (3х3) типу int
arr2_2 = arr2_1.reshape((3,3))
...
print(arr2_2)
print(arr2_2.dtype)
arr2_2.astype('int')

[[False False False]
 [False False False]
 [False False False]]
bool


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [70]:
### ЗАВДАННЯ 2.3: створити  2-мірний масив парних чисел в інтервалі 10-21
arr2_3 = np.arange(10,21,2)
arr2_4 = arr2_3.reshape(2,3)

...
print(arr2_4)


[[10 12 14]
 [16 18 20]]


## 3. Доступ до  елементів масива

### ПРИКЛАДИ

In [11]:
arr = np.array([10, 6, 7, 21, 44]) 
print(arr)

# 1-й елемент 
print(arr[0])
# 3-й елемент
print(arr[2])
# останній елемент
print(arr[-1])

[10  6  7 21 44]
10
7
44


In [12]:
# створити 2-мірний масив з цілих чисел з інтервалу 10-50
arr = np.random.randint(10, 50, (4,4))
print(arr)

[[34 42 11 28]
 [30 41 31 47]
 [10 28 24 10]
 [45 42 10 17]]


In [13]:
# отримати значення останнього елемента в 2 рядку
el = arr[1, -1]
print(el)

47


In [14]:
# отримати значення останнього рядка
vect = arr[-1]
print(vect)

[45 42 10 17]


In [15]:
# отримати `зріз` з 1 по 2 рядок
mat = arr[0:2]
print(mat)

[[34 42 11 28]
 [30 41 31 47]]


In [16]:
# вилучити 2 та 3 стовбчики `arr`
mat = arr[0:4, 1:3]
print(mat)

[[42 11]
 [41 31]
 [28 24]
 [42 10]]


In [20]:
# вилучити непарні рядки `arr`
mat = arr[0:4:2]
print(mat)

[[34 42 11 28]
 [10 28 24 10]]


In [21]:
# фільтрувати елементи масива за умовою
els = arr[arr > 20]
print(els)

[34 42 28 30 41 31 47 28 24 45 42]


### ЗАВДАННЯ 3

In [4]:
### ЗАВДАННЯ 3.1: створити масив 4х5 нормально розподілений випадкових чисел 3 інтервалу [10 - 100]
arr3_1 = np.random.randint(10, 100, (4,5))
print(arr3_1)

[[44 14 99 62 48]
 [49 67 84 88 40]
 [40 14 60 10 90]
 [23 41 41 25 80]]


In [8]:
### ЗАВДАННЯ 3.2:  вивести 3-елемент в 2-му рядку
el3_2 = arr3_1[1,2]
print(el3_2)

84


In [9]:
### ЗАВДАННЯ 3.3:  вивести 2-й рядок масива `arr3_1`
vect3_3 = arr3_1[1]
print(vect3_3)

[49 67 84 88 40]


In [25]:
### ЗАВДАННЯ 3.4:  вивести 3 колонку масива `arr3_1`
vect3_4 = arr3_1[0:4,2:3]
print(vect3_4)

[[99]
 [84]
 [60]
 [41]]


In [30]:
### ЗАВДАННЯ 3.5: вивести матрицю  з 2 та 3 рядка та 2 та 3 колонки масива `arr3_1`
mat3_5 = arr3_1[1:3,1:3]

print(mat3_5)


[[67 84]
 [14 60]]


## 4. Матричні компоненти масива

### ПРИКЛАДИ

In [27]:
# створити одиничну матрицю розміру 3х3
mat = np.eye(3)
print(mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
# створити матрицю із заданою диагоналлю
mat = np.diag([1,2,3,4,5])
print(mat)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [32]:
# вилучити головну діагональ матриці `diag`
mat = np.random.rand(5,5)
print(mat, end="\n...\n")
print(np.diag(mat))

[[0.52731359 0.83384587 0.57515875 0.35300642 0.10148244]
 [0.88678574 0.53921445 0.0472987  0.71465548 0.06821511]
 [0.07244793 0.65440399 0.64247318 0.35674674 0.31515921]
 [0.04195817 0.74732311 0.08244535 0.48509881 0.18242815]
 [0.10859245 0.53751517 0.66993568 0.45226871 0.46212285]]
...
[0.52731359 0.53921445 0.64247318 0.48509881 0.46212285]


In [33]:
# транспонувати матрицю `mat` (https://ru.wikipedia.org/wiki/Транспонированная_матрица)
mT = np.transpose(mat)
print(mT)

[[0.52731359 0.88678574 0.07244793 0.04195817 0.10859245]
 [0.83384587 0.53921445 0.65440399 0.74732311 0.53751517]
 [0.57515875 0.0472987  0.64247318 0.08244535 0.66993568]
 [0.35300642 0.71465548 0.35674674 0.48509881 0.45226871]
 [0.10148244 0.06821511 0.31515921 0.18242815 0.46212285]]


In [34]:
# отримати детермінант матриці `det` (https://ru.wikipedia.org/wiki/Определитель)
print(np.linalg.det(mat))

-0.007885692862569557


In [35]:
# отримати зворотню матриці `det` (https://ru.wikipedia.org/wiki/Обратная_матрица)
invM = np.linalg.inv(mat)
print(invM)

[[  3.8011375   -1.06480914  -8.61013466   0.46163412   5.01216416]
 [  3.36811921  -1.95622034  -6.05499037   2.30126593   2.77006246]
 [ -3.17281086   1.85060769  10.35867938  -2.91785993  -5.48899129]
 [ -7.75195815   4.51041318  16.6944743   -2.48619588  -9.36732734]
 [  7.37543566  -4.57146524 -22.28929506   3.8779986   14.88908508]]


### ЗАВАДАННЯ 4

In [41]:
# ЗАВДАННЯ 4.1: створити квадратну матрицю з 36 рівномірно розподілених цілих 
# елементів з інтервалу 100 - 200
mat4_1 = np.random.randint(100, 200, (6,6))
print(mat4_1)

[[167 134 118 151 134 198]
 [117 138 110 104 135 162]
 [150 116 111 191 165 111]
 [101 165 103 171 126 196]
 [187 145 126 113 151 195]
 [110 160 104 152 143 132]]


In [43]:
# ЗАВДАННЯ 4.2: вивести головну діагональ матниці `mat4_1`
diag4_2 = np.diag(mat4_1)
print(diag4_2)

[167 138 111 171 151 132]


In [44]:
# ЗАВДАННЯ 4.3: транспонувати матрицю 'mat4_1'
trans4_3 = np.transpose(mat4_1)
print(trans4_3)

[[167 117 150 101 187 110]
 [134 138 116 165 145 160]
 [118 110 111 103 126 104]
 [151 104 191 171 113 152]
 [134 135 165 126 151 143]
 [198 162 111 196 195 132]]


In [46]:
# ЗАВДАННЯ 4.4: вирахувати зворотню до 'mat4_1' матрицю 
inv4_4 = np.linalg.inv(mat4_1)
print(inv4_4)

[[ 6.79917353e-04 -2.74703844e-02 -2.85291900e-03 -2.97600248e-03
   1.97025279e-02  1.04057286e-02]
 [ 2.07765736e-03 -2.01390472e-02 -1.58380491e-02 -5.83518597e-03
   7.35930880e-03  3.27106378e-02]
 [ 1.45912469e-01  7.23486009e-02 -3.92507083e-02 -1.02108937e-01
  -1.26425501e-01  6.37273535e-02]
 [ 1.58861565e-02 -6.14769581e-03  1.73041648e-03 -1.49179680e-03
  -1.36701409e-02  4.67016028e-03]
 [-9.92146549e-02 -2.43572693e-03  3.76572946e-02  5.72370889e-02
   6.35538908e-02 -5.87299121e-02]
 [-2.88569167e-02  1.88943815e-05  9.71186502e-03  2.97134003e-02
   2.11601489e-02 -3.27080598e-02]]


## 5. Операції над масивами

### ПРИКЛАДИ

In [47]:
# задати вектор з 10 елементів
vect = np.array([1, 3, 2, -3, 5, 0])

In [ ]:
# вирахувати суму елеметнів
s = np.sum(vect)

# знайти мінімальний ел-т
m = np.min(vect)

# відсортувати вектор по зростанню
vs = np.sort(vect)

# знайти середнє значення
mid = np.average(vect)
...

In [48]:
# матриця 3х3 сконструйована різними методами
mat = np.array([np.arange(1,4), [-2, 4, 6], np.full(3,77)])
print(mat)

[[ 1  2  3]
 [-2  4  6]
 [77 77 77]]


In [58]:
# сума по колонкам `axis=0`
s = np.sum(mat, axis=0)
print(s)

[76 83 86]


In [53]:
# мінімум по рядкам
m = np.min(mat, axis=1)
print(m)

[ 1 -2 77]


In [54]:
# збільшити ел-ти масива вдвічі
v2 = mat * 2
print(v2)

[[  2   4   6]
 [ -4   8  12]
 [154 154 154]]


In [55]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
N = np.array([[1,1,1],[2,2,2],[3,3,3]])
print(M, N, sep="\n")

[[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]
[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [56]:
# перемножити елементи матриць M, N
K = M * N
print(K)
# або ->
K = np.multiply(N, M)
print(K)

[[ 1  2  3]
 [ 8 -6 12]
 [21 24  0]]
[[ 1  2  3]
 [ 8 -6 12]
 [21 24  0]]


In [59]:
# поелементний поділ
K = N / M
print(K)

[[ 1.          0.5         0.33333333]
 [ 0.5        -0.66666667  0.33333333]
 [ 0.42857143  0.375              inf]]


C:\Users\Admin\AppData\Local\Temp\ipykernel_7672\3347190385.py:2: RuntimeWarning: divide by zero encountered in true_divide
  K = N / M


In [60]:
# скалярне множення матриць (https://ru.wikipedia.org/wiki/Умножение_матриц)
prod = np.dot(N, M)
print(prod)

[[12  7  9]
 [24 14 18]
 [36 21 27]]


In [120]:
# возвести матрицю `prod` в ступінь 3
pmat = np.linalg.matrix_power(prod, 3)
print(pmat)

[[ 33708  19663  25281]
 [ 67416  39326  50562]
 [101124  58989  75843]]


In [61]:
# додати елементи до 1-вимірного масива
mat = np.array([1,2,3])
mat = np.append(mat, [5,6,7,8])
print(mat)

[1 2 3 5 6 7 8]


In [62]:
# вставити елемент `4` в масив після 3-го елемента
mat = np.insert(mat, 3, 4)
print(mat)

[1 2 3 4 5 6 7 8]


In [63]:
# видалити елемент з індексом 6
mat = np.delete(mat, 6)
print(mat)

[1 2 3 4 5 6 8]


In [64]:
#  копіювання та присвоювання масивів
M = np.random.randint(1, 10, 5 )
print(M)

# присвоїти масив `M` в `N`
N = M
print(N)
print(id(M), id(N))

# копіювати масив `M` в `K`
K = np.copy(M)
print(K)
print(id(M), id(K))

[6 8 4 1 1]
[6 8 4 1 1]
2589712284624 2589712284624
[6 8 4 1 1]
2589712284624 2589712173552


In [65]:
# конкатенація масивів по рядкам
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])
arr3 = np.concatenate((arr1, arr2), axis=0)
print(arr3)
# по колонкам `axis = 1`
arr4 = np.concatenate((arr1, arr2), axis=1)
print(arr4)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]
[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


### ЗАВДАННЯ 5

In [84]:
# ЗАВДАННЯ 5.1: просумувати по рядкам масив випадкових чисел розмірностю 3х4
mat5_1 = np.random.randint(3,9,(3,4))
print(mat5_1)
sum_mat5_1 = np.sum(mat5_1,axis=1)
print(sum_mat5_1)

[[5 5 5 3]
 [5 3 4 4]
 [7 7 5 7]]
[18 16 26]


In [85]:
# ЗАВДАННЯ 5.2: знайти мінімальний елемент матриці `sum_mat5_1`
min_mat5_1 = np.min(mat5_1)
print(min_mat5_1)

3


In [86]:
# ЗАВДАННЯ 5.3: створити масив додавши до елементів `mat5_1`  число 100
mat5_3 = mat5_1 + 100
print(mat5_3)

[[105 105 105 103]
 [105 103 104 104]
 [107 107 105 107]]


In [93]:
# ЗАВДАННЯ 5.4: помножити матрицю `mat5_1` на головну діагональ матриці `mat5_3`
print(mat5_3)
print(mat5_1)
mat5_4 = np.dot(mat5_1.T, np.diag(mat5_3))
#mat5_4 = mat5_1.T * np.diag(mat5_3)
print(mat5_4)

[[105 105 105 103]
 [105 103 104 104]
 [107 107 105 107]]
[[5 5 5 3]
 [5 3 4 4]
 [7 7 5 7]]
[1775 1569 1462 1462]


In [119]:
# ЗАВДАННЯ 5.5: додати справа до матриці `mat5_3` матрицю `mat5_4` 
# вивести ранг отриманої матриці
#print(mat5_3.T,np.array([mat5_4]).T)
mat5_5 = np.concatenate((mat5_3.T,np.array([mat5_4]).T),axis=1)

                        
print(mat5_5)

[[ 105  105  107 1775]
 [ 105  103  107 1569]
 [ 105  104  105 1462]
 [ 103  104  107 1462]]
